### ISSUE TITLE
4 seconds to create the image

### ISSUE THREAD

**Issue by voltea** [frinyvonnick/node-html-to-image#79] opened 2020-11-09 19:44 UTC
I have a simple html with Style and some divs but for some reason it takes almost 4 seconds to generate the image

`const img = await nodeHtmlToImage({
          output:'imagen4.png',
          quality:'1',
          html: `<html>
          <style type="text/css">
          li{
            list-style:none
          }
          body{
            width: 500px;height: 250px; border: solid 1px;
          }
          .head{
            font-weight: bold;font-family:system-ui;font-size: 15px; text-align:center; border-bottom: solid 1px;
        
          }
          .baj{
            font-weight: bold;font-family:system-ui;font-size: 30px; text-align:center; border-bottom: solid 1px; border-top: solid 1px;
        
          }
          .fl{
            float: left;
            margin-right: 10px;
          }
          .image{
            text-align: center;
            margin-top: 20px;
            
          }
          .cajas{
              border-right: solid 1px;
              padding-right: 10px;
          }
          .ulformat{
            margin-top: 0px;
            margin-bottom: 0px;
            margin-left: -30px; 
            font-size: 12px;
          }
          </style>
          <body >
            <div class='head'><img src='https://Logoapp/img/2020/logo_negro.png' style='width: 95px;'></div>
            <div class="fl" >
              <ul class="ulformat">
              <li>
                Fecha	:
              </li>
                <li>
                  Nombre	:
                </li>
                <li>
                  Direccion:
                </li>
                
              </ul>
              
            </div>
            <div>
              <ul class="ulformat">
              <li>
                  {{date_in}}
                </li>
                <li>
                  {{name}}
                </li>
                <li>
                  {{address}}
                </li>
               
              </ul>
            </div>
            <div>
  
            <div class="baj">
            N de orden: {{order_id}}
            </div>
          
          <div class='image'>
          <img style='text-align:center;' src='data:image/png;base64,{{barcode}}'>
          </div>
  
  
          </body>
        </html>
        `,
        content: { task_id: req.body.task_id, order_id: req.body.order_id, barcode: barra, address: req.body.address, name: req.body.name, date_in: req.body.date_in }
        });`

Please Help

**Comment by frinyvonnick** [comment] 2020-11-12 07:49
Hi @voltea 👋 

Thank you for posting this issue. The image `https://logoapp/img/2020/logo_negro.png` is not available so I can't reproduce your issue. Can you provide a working example of your problem, please?

**Comment by frinyvonnick** [comment] 2021-06-26 10:20
I close this issue. Feel free to reopen it.

**Closed by frinyvonnick** 2021-06-26 10:20 UTC
Labels: needs reproduction
