### ISSUE TITLE
 error while loading shared libraries: libX11-xcb.so.1: cannot open shared object file: No such file or directory 

### ISSUE THREAD

**Issue by smallbitt** [frinyvonnick/node-html-to-image#31] opened 2020-05-26 14:36 UTC
Hi,
A project with NodeJS latest version with express.
In localhost is everything fine and working perfectly, but when I deploy on Heroku and try to run the function I get this error.

`Failed to launch the browser process! /app/node_modules/node-html-to-image/node_modules/puppeteer/.local-chromium/linux-722234/chrome-linux/chrome: error while loading shared libraries: libX11-xcb.so.1: cannot open shared object file: No such file or directory`

Its something chromium related, do you have any fix for this?

thanks

**Comment by frinyvonnick** [comment] 2020-05-27 07:06
Hi @smallbitt,

I'm not familiar with Heroku but it seems you have to install a specific buildpack if you want to use libraries that uses Puppeteer. Read more in this [issue](https://github.com/puppeteer/puppeteer/issues/758) or in Puppeteer's [troubleshooting section](https://github.com/puppeteer/puppeteer/blob/master/docs/troubleshooting.md#running-puppeteer-on-heroku).

Hope it will help. Please close this issue if it fixes your problem 👍

**Comment by DharmarajX24** [comment] 2020-07-01 07:17
@smallbitt I had got the same error but it was on GCP Ubuntu VM.

https://medium.com/@cloverinks/how-to-fix-puppetteer-error-ibx11-xcb-so-1-on-ubuntu-152c336368

This fixes the issue but I doubt how will you use it on Heroku.. you need access the command line.

**Comment by sajib21** [comment] 2020-07-24 13:52
Were you able to solve this problem? 
I tried passing `puppeteerArgs: { args: ["--no-sandbox", "--disable-setuid-sandbox"] }` in like 

    nodeHtmlToImage({
        html: "...",
        content: {...},
        puppeteerArgs: { args: ["--no-sandbox", "--disable-setuid-sandbox"] }
    );
But it didn't work.

**Comment by sajib21** [comment] 2020-07-25 09:43
Update, I think you and I had the same problem. I resolved it and wrote about it in this issue: https://github.com/frinyvonnick/node-html-to-image/issues/49#issuecomment-663834469

**Comment by frinyvonnick** [comment] 2020-07-27 12:36
@smallbitt did you try the fixes in the previous messages?

**Comment by frinyvonnick** [comment] 2020-09-16 12:45
I close this issue, feel free to reopen it if you have further information.

**Comment by yaron-shamul** [comment] 2021-12-14 21:13
I have the same issue while working with async_html:

```
requests_html.AsyncHTMLSession()
requested_page.html.arender(timeout=timeout)
```

I'm also getting this error bellow when trying to run chrome from default path:

`./chrome: error while loading shared libraries: libXcomposite.so.1: cannot open shared object file: No such file or directory`

**Comment by yaron-shamul** [comment] 2021-12-14 21:14
> I close this issue, feel free to reopen it if you have further information.

can you please open this issue again?

**Comment by frinyvonnick** [comment] 2021-12-15 09:59
Hi @yaron-shamul,

Can you provide everything to reproduce your issue, please?

**Comment by yaron-shamul** [comment] 2021-12-15 10:05
Yeah sure, take a look on this issue:
https://github.com/pyppeteer/pyppeteer/issues/341

**Comment by frinyvonnick** [comment] 2021-12-15 10:27
I don't understand. You are linking a python project. node-html-to-image is a Javascript project running on node. How is it related?

**Comment by yaron-shamul** [comment] 2021-12-15 10:56
I saw the exact same error and wanted to solve it.

**Comment by frinyvonnick** [comment] 2021-12-15 13:01
I think this issue is more related to puppeteer.

**Comment by yaron-shamul** [comment] 2021-12-15 13:06
pyppeteeris a module working over puppeteer, so the issue is related as the solution of your issue is related

**Comment by frinyvonnick** [comment] 2022-02-12 20:06
This issue is really old and we moved from puppeteer v3 to v13 in latest version of node-html-to-image. So I close this issue.

**Closed by frinyvonnick** 2022-02-12 20:06 UTC
Labels: bug, needs reproduction
