### ISSUE TITLE
selector issue

### ISSUE THREAD

**Issue by jr0dd** [frinyvonnick/node-html-to-image#151] opened 2022-01-11 17:22 UTC
I am trying to use the selector option to capture just a particular element on the page and I absolutely can not get it to work.

js code
```
    const image = await nodeHtmlToImage({
      html: 'https://www.whalestream.com/market-data/top-options-flow?flow=all',
      selector: 'div[class="mx-auto max-w-3xl px-4 space-y-5"]',
      puppeteerArgs: {
        args: [
          '--disable-gpu',
          '--no-sandbox',
          '--disable-setuid-sandbox',
          '--disable-dev-shm-usage',
          '--headless'
        ]
      }
    })
```

logs
```
/Users/j_r0dd/Code/wyoa-bot/node_modules/node-html-to-image/src/screenshot.js:28
      throw Error('No element matches selector: ' + selector)
```

selector copy from browser
```
#top-flow-container > div.mx-auto.max-w-3xl.px-4.space-y-5
```

html code of where to capture
```
<div class="mx-auto max-w-3xl px-4 space-y-5">
```

**Comment by frinyvonnick** [comment] 2022-01-12 08:04
Hello @jr0dd 👋 

Thank you for posting this issue. The html property only accept HTML and not urls. If you want to make screenshot of existing pages I recommend using puppeteer directly 😄

**Comment by jr0dd** [comment] 2022-01-12 14:25
> Hello @jr0dd 👋 
> 
> 
> 
> Thank you for posting this issue. The html property only accept HTML and not urls. If you want to make screenshot of existing pages I recommend using puppeteer directly 😄 

Ah, I see. I had used this library for just html code for other things and didn't realize it wasn't for URL's 😳

**Comment by frinyvonnick** [comment] 2022-01-12 15:12
No problem! Maybe we should add an error if an url is provided 🤔 ?

**Comment by frinyvonnick** [comment] 2022-02-08 14:10
I close this issue since it was a misusage and not a bug 😄

**Closed by frinyvonnick** 2022-02-08 14:10 UTC
