### ISSUE TITLE
TypeError [ERR_INVALID_ARG_TYPE]: The "original" argument must be of type function

### ISSUE THREAD

**Issue by Behkha** [frinyvonnick/node-html-to-image#50] opened 2020-07-24 23:06 UTC
this error happens when i just require the package and run node index.js 
what is the solution?

**Comment by frinyvonnick** [comment] 2020-07-25 09:03
Hi @Behkha 👋 

Thank you for opening this issue. Can you share the code you wrote in index.js please?

**Comment by Behkha** [comment] 2020-08-02 10:28
i just used the examples nothing more

**Comment by frinyvonnick** [comment] 2020-08-02 10:57
Can you share me some environment information (node version, npm version, os, ...)

**Comment by Behkha** [comment] 2020-08-02 12:39
node v8.11.4
npm v6.13.1
os: windows

**Comment by frinyvonnick** [comment] 2020-08-02 15:11
Could you provide me the error with the full stacktrace please?

**Comment by Behkha** [comment] 2020-08-02 22:26
`const nodeHtmlToImage = require('node-html-to-image')`

This is the only code in my js file and below is the stacktrace

internal/util.js:209
    throw new errors.TypeError('ERR_INVALID_ARG_TYPE', 'original', 'function');
    ^

TypeError [ERR_INVALID_ARG_TYPE]: The "original" argument must be of type function
    at promisify (internal/util.js:209:11)
    at Object.<anonymous> (E:\Programming\My Projects\Tests\html-to-image-converter\node_modules\extract-zip\index.js:11:18)
    at Module._compile (module.js:652:30)
    at Object.Module._extensions..js (module.js:663:10)
    at Module.load (module.js:565:32)
    at tryModuleLoad (module.js:505:12)
    at Function.Module._load (module.js:497:3)
    at Module.require (module.js:596:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (E:\Programming\My Projects\Tests\html-to-image-converter\node_modules\node-html-to-image\node_modules\puppeteer\lib\BrowserFetcher.js:21:17)

**Comment by mamidd** [comment] 2020-08-07 08:06
I have similar error and when it goes in error it generates 4 zombie processes.

I use this dockerfile to run the code:
FROM node:12.18.0-buster-slim@sha256:97da8d5023fd0380ed923d13f83041dd60b0744e4d140f6276c93096e85d0899

RUN  apt-get update \
    && apt-get install -y wget gnupg ca-certificates \
    && wget -q -O - https://dl-ssl.google.com/linux/linux_signing_key.pub | apt-key add - \
    && sh -c 'echo "deb [arch=amd64] http://dl.google.com/linux/chrome/deb/ stable main" >> /etc/apt/sources.list.d/google.list' \
    && apt-get update \
    # We install Chrome to get all the OS level dependencies, but Chrome itself
    # is not actually used as it's packaged in the node puppeteer library.
    # Alternatively, we could could include the entire dep list ourselves
    # (https://github.com/puppeteer/puppeteer/blob/master/docs/troubleshooting.md#chrome-headless-doesnt-launch-on-unix)
    # but that seems too easy to get out of date.
    && apt-get install -y google-chrome-stable \
    && rm -rf /var/lib/apt/lists/* \
    && wget --quiet https://raw.githubusercontent.com/vishnubob/wait-for-it/master/wait-for-it.sh -O /usr/sbin/wait-for-it.sh \
    && chmod +x /usr/sbin/wait-for-it.sh

The code is:
const buffer = Buffer.from(await nodeHtmlToImage({
                 html: ` <html>
                            <head>
                                <style>
                                    {{{ css }}}
                                </style>
                            </head>
                            <body>
                                {{{ html }}}
                            </body>
                        </html>`,
                content: {
                    css,
                    html,
                },
                type: 'jpeg',
                quality: 60,
                puppeteerArgs: {
                    args: ['--no-sandbox'],
                    defaultViewport: {
                        width: 1200,
                        height: 300,
                    },
                },
            }))
            console.log('buffer GENERATED', typeof buffer)

            const imageResized = await sharp(buffer).resize(300).toBuffer()
            console.log('image RESIZED', typeof imageResized)

            const base64 = Buffer.from(imageResized).toString('base64')
            console.log('base64 GENERATED', typeof base64)

            return base64

**Comment by haffoudhi** [comment] 2020-08-30 20:20
It occurs with the latest version of puppeteer.
Your scripts should work properly in a lower version.

Try this script:
`npm i -save puppeteer@1.7.0`

**Comment by bandarawaththa** [comment] 2020-09-07 04:10
It also happened to me with just basic code
`const nodeHtmlToImage = require('node-html-to-image')`
this is the error in console 
`internal/util.js:214
    throw new errors.TypeError('ERR_INVALID_ARG_TYPE', 'original', 'function');
    ^

TypeError [ERR_INVALID_ARG_TYPE]: The "original" argument must be of type function
    at promisify (internal/util.js:214:11)
    at Object.<anonymous> (/home/charaka/MEGAsync/Docs/Tutopiya/Classroom/tutopiya-classroom/node_modules/extract-zip/index.js:11:18)
    at Module._compile (module.js:653:30)
    at Object.Module._extensions..js (module.js:664:10)
    at Module.load (module.js:566:32)
    at tryModuleLoad (module.js:506:12)
    at Function.Module._load (module.js:498:3)
    at Module.require (module.js:597:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/home/charaka/MEGAsync/Docs/Tutopiya/Classroom/tutopiya-classroom/node_modules/puppeteer/lib/BrowserFetcher.js:21:17)`

node -v -> v12.18.3
npm -v -> v6.14.6
Distributor ID:	Kali
Release:	2020.3

what can I do ?

**Comment by impactcolor** [comment] 2020-09-23 20:53
@Behkha  try this, I think it will work.
`const beMorePolite = question => {
if(question) {
return 'more people will be happy to help'
} else {
return 'go suck a lemon'
}
}`

**Comment by frinyvonnick** [comment] 2020-09-24 06:58
@impactcolor please be respectful and welcoming. I just added a [code of conduct](https://github.com/frinyvonnick/node-html-to-image/blob/master/CODE_OF_CONDUCT.md), I invite you to read it 👍

**Comment by frinyvonnick** [comment] 2020-09-24 07:11
@Behkha I reproduced your issue using node v8:

![image](https://user-images.githubusercontent.com/13099512/94112458-c8021680-fe45-11ea-839b-851bca5c30ef.png)

As stated in this [comment](https://github.com/puppeteer/puppeteer/issues/6149#issuecomment-663833688), pupeteer 3.0.0 only support node v10.18.1+. Please upgrade your node version to use `node-html-to-image`.

**Comment by frinyvonnick** [comment] 2020-12-01 14:38
I close this issue since there is no answer for a long time. Feel free to reopen it.

**Closed by frinyvonnick** 2020-12-01 14:38 UTC
Labels: bug, needs reproduction

**Comment by fx1357** [comment] 2020-12-26 04:28
> It occurs with the latest version of puppeteer.
> Your scripts should work properly in a lower version.
> 
> Try this script:
> `npm i -save puppeteer@1.7.0`


This leads to another error.
-->Uncaught TypeError: Cannot read property 'bind' of undefined

**Comment by frinyvonnick** [comment] 2020-12-26 09:33
Hi @fx1357 👋 Which version of node do you use?

**Comment by fx1357** [comment] 2021-01-11 11:47
> Hi @fx1357 👋 Which version of node do you use?

my version is v14.15.3

I got to know the cause.
the error occurs when importing and writing in  <script> of vue.js.
It must not be compatible with vue.js.
