### ISSUE TITLE
Cannot export buffer with electron app.

### ISSUE THREAD

**Issue by khoa-nv** [frinyvonnick/node-html-to-image#117] opened 2021-06-30 14:30 UTC
Hello, I have a problem when using this package in my local server with an electron app. Everything working well done when developing, but after building the production application nodeHtmlToImage function was throw into an empty error. Anybody can give me any advice to solve it?

**Comment by frinyvonnick** [comment] 2021-06-30 14:54
Hello @khoa-nv 👋 

Thank you for posting this issue. Can you provide a repository that reproduce this error, please?

**Comment by khoa-nv** [comment] 2021-06-30 14:59
> Hello @khoa-nv 👋
> 
> Thank you for posting this issue. Can you provide a repository that reproduce this error, please?

Thank you for your response. This is my project. I am building an app to control the Printer.
[https://github.com/khoa-nv/katec_printer_server/blob/master/factories/billFactory.js](url)

**Comment by frinyvonnick** [comment] 2021-06-30 15:08
Can you also give some steps to execute in order to see the problem?

**Comment by khoa-nv** [comment] 2021-06-30 15:32
It is too hard, bro.  Because it works with my company website. I just update my code. Please:
Clone my "t

1. - est" branch.
2. - Run `npm install` to install dependencies
3. - After that run `npm run app` to start the application.
4. On your browser, access to `http://localhost:60222/test` you will receive the buffer, that's what I wish.
5. To see my problem, please run `npm run build` to build the product. Run release app and access `http://localhost:60222/test` you will see the error was thrown on my catch. Please see the getPrintTest in the billFactory file.

**Comment by khoa-nv** [comment] 2021-07-01 03:24
The issue doesn't come from your package, it's from Puppeteer. I just try to use puppeteer and got the same problem :(((

**Comment by frinyvonnick** [comment] 2021-07-01 06:44
@khoa-nv can you post a link that explain the issue?

**Comment by khoa-nv** [comment] 2021-07-01 06:48
> @khoa-nv can you post a link that explain the issue?

hmm. I can solve the problem by add `executablePath` to `puppeteerArgs`. 
This post [https://stackoverflow.com/questions/62602604/puppeteer-fails-in-react-app-after-running-electron-builder](url)  is not entirely my problem but it's the same. I guess the puppeteer cannot found chromium.

**Comment by frinyvonnick** [comment] 2021-07-02 07:29
Do you think it could be interesting to add some explanation about it in the README or is it to specific to your technical stack?

**Comment by khoa-nv** [comment] 2021-07-06 01:23
> Do you think it could be interesting to add some explanation about it in the README or is it to specific to your technical stack?

I don't know does anyone got the same problem. My way is the only temporary solution to make it work.

**Comment by frinyvonnick** [comment] 2022-02-08 14:38
I close this issue since it is related to puppeteer and not node-html-to-image.

**Closed by frinyvonnick** 2022-02-08 14:38 UTC
Labels: needs reproduction
