### ISSUE TITLE
Not waiting to output image

### ISSUE THREAD

**Issue by crb596** [frinyvonnick/node-html-to-image#104] opened 2021-04-01 08:21 UTC
I am trying to output a large image (10800x7200) and most of the time the output is as expected. However about every fourth image or so is only partially rendered. It is as if little squares are missing after a certain point and you can see where it just outputted before finishing.

![example](https://user-images.githubusercontent.com/57211534/113264882-89fa1980-92e4-11eb-931d-9f7f2651acc8.png)

This is a png which should be rendering a transparent to white gradient and would have text on the bottom. As it would be impossible to see white or transparent on this page I put it over a black background for demonstration purposes. I apologize how hard it is to see since the transparent section renders first but if you look at the top you can see a white hue and about half way down it cuts off.

I have tried all the various waitUntil: options but none cure this.

**Comment by frinyvonnick** [comment] 2021-06-26 10:03
Hi @crb596 👋 Thank you for posting this issue 🙏 

Can you share the code you used so I could reproduce your issue?

**Comment by frinyvonnick** [comment] 2022-02-12 20:19
I close this issue since I did not get any answer.

**Closed by frinyvonnick** 2022-02-12 20:19 UTC
Labels: needs reproduction
