### ISSUE TITLE
Unable to launch browser, error message: Failed to launch the browser process!

### ISSUE THREAD

**Issue by prioarief** [frinyvonnick/node-html-to-image#178] opened 2022-09-06 07:09 UTC
Unable to launch browser, error message: Failed to launch the browser process!
Running as root without --no-sandbox is not supported. See https://crbug.com/638180.

**Comment by sankara-sabapathy** [comment] 2022-09-10 14:01
+++Same error

**Comment by sankara-sabapathy** [comment] 2022-09-10 14:01
Error:
Error: Unable to launch browser, error message: Could not find expected browser (chrome) locally. Run `npm install` to download the correct Chromium revision (982053).

**Comment by RickRyan26** [comment] 2022-09-30 21:37
same error

**Comment by ShalaQweghen** [comment] 2022-10-05 19:32
Try passing this `puppeteerArgs: { args: ['--no-sandbox'] }` to `nodeHtmlToImage` function.

**Comment by macsimtv** [comment] 2022-10-19 15:28
Not working :/

**Comment by frinyvonnick** [comment] 2022-10-22 16:51
Hello there 👋 

I see a lot a comments here. I need some explanations and instructions (step by step) to reproduce easily your use cases. Otherwise I won't be able to help you.

**Comment by bpeters** [comment] 2022-11-08 21:56
I believe they are probably running this in a aws-lambda env. It looks like your latest unrelease code fixes the issue with the custom puppeteer option.

**Comment by frinyvonnick** [comment] 2023-01-18 10:07
I just released [3.3.0](https://github.com/frinyvonnick/node-html-to-image/releases/tag/v3.3.0) version which contain a feature to customise which puppeteer library node-html-to-image uses. As @bpeters it might help you making node-html-to-image work in a cloud context. Here is the documentation : https://github.com/frinyvonnick/node-html-to-image#using-different-puppeteer-libraries

Could you close the issue if it fixes it, please?

**Comment by frinyvonnick** [comment] 2023-08-05 09:10
Without any new answer I close this issue. Feels free to reopen it 👍

**Closed by frinyvonnick** 2023-08-05 09:10 UTC
Labels: needs reproduction

**Comment by baolongt** [comment] 2024-07-15 05:02
If you use some cloud function
try to run 
node node_modules/puppeteer/install.js
before deployed
